version: "3.9"
services:
  monitor-dashboard:
    build:
      context: ./monitor
    image: monitor-dashboard:latest
    container_name: monitor-dashboard
    ports:
      - "8000:8000"
    environment:
      - MONITOR_MODE=winrm
      - WINRM_HOST=host.docker.internal
      - WINRM_PORT=5985
      - WINRM_USE_SSL=false
      - WINRM_USERNAME=REPLACE_WITH_USERNAME
      - WINRM_PASSWORD=REPLACE_WITH_PASSWORD
      - TARGET_DIRS=C:\\Program Files (x86)\\Splashtop;C:\\Program Files (x86)\\ATERA Networks;C:\\Program Files\\Splashtop;C:\\Program Files\\ATERA Networks
      - SAMPLE_INTERVAL_SECONDS=1
      - PERSIST_PATH=/app_data/metrics.json
    volumes:
      - monitor_data:/app_data
    restart: unless-stopped

volumes:
  monitor_data:
